steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/Tejas-100925231/dockerfile:$SHORT_SHA', 'Assignment2/']
 
 
  # Step 2: Push the Docker image to the Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/Tejas-100925231/dockerfile:$SHORT_SHA']
 
options:
  logging: GCS_ONLY
