steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/academic-emblem-411717/tejas-100925231/dockerfile:$COMMIT_SHA', 'Assignment2/']
 
  # Step 2: Push the Docker image to the Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/academic-emblem-411717/tejas-100925231/dockerfile:$COMMIT_SHA']
    
   #step 3 Deploy Docker container to Cloud Run using Google Cloud SDK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy dockerfile \
          --image us-central1-docker.pkg.dev/academic-emblem-411717/tejas-100925231/dockerfile:$COMMIT_SHA \
          --platform managed \
          --region us-central1
 
images:
  - 'us-central1-docker.pkg.dev/academic-emblem-411717/tejas-100925231/dockerfile:$COMMIT_SHA'
 
options:
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET